/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Text;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const StoreInfo = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([Category], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Float64, Category, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'deleteCategory' : IDL.Func([Category], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, Category, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Text;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const StoreInfo = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func([Category], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, Category, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'deleteCategory' : IDL.Func([Category], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStoreInfo' : IDL.Func([], [StoreInfo], ['query']),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, Category, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };