/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'unit' : string,
  'category' : Category,
  'price' : number,
}
export interface StoreInfo {
  'hours' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<[Category], undefined>,
  'addProduct' : ActorMethod<
    [string, number, Category, string, boolean],
    undefined
  >,
  'deleteCategory' : ActorMethod<[Category], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStoreInfo' : ActorMethod<[], StoreInfo>,
  'updateProduct' : ActorMethod<
    [bigint, string, number, Category, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];